export const jadwalKonseling = [
  {
    id: 1,
    waktu: "Hari ini, 10.00 - 11.00",
    namaSiswa: "Ahmad Junaidi",
    kelas: "XI TKJ 4",
    guruBK: "Guru BK SMK Telkom",
    jenisSesi: "Online",
    jenisKonseling: "Karir",
    topikKonseling: "Karir",
    tanggalPengajuan: "15 Oktober 2025",
    tanggalKonseling: "20 Oktober 2025",
    linkGoogleMeet: "https://meet.google.com/abc-defg-hij",
    deskripsi: "Siswa ingin berkonsultasi mengenai pilihan karir setelah lulus.",
    status: "Disetujui",
    catatanSiswa: "Saya ingin membahas tentang prospek kerja di bidang IT.",
    catatanGuruBK: "Siswa menunjukkan minat yang tinggi pada bidang teknologi informasi.",
  },
  {
    id: 2,
    waktu: "Hari ini, 10.00 - 11.00",
    namaSiswa: "Nadia Putri",
    kelas: "XI RPL 2",
    guruBK: "Ibu Astuti",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Pendidikan",
    topikKonseling: "Pendidikan",
    tanggalPengajuan: "14 Oktober 2025",
    tanggalKonseling: "20 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa mengalami kesulitan dalam mengikuti pelajaran matematika.",
    status: "Disetujui",
    catatanSiswa: "Saya kesulitan memahami materi kalkulus.",
    catatanGuruBK: "Perlu pendampingan khusus untuk materi matematika lanjutan.",
  },
  {
    id: 3,
    waktu: "Hari ini, 12.00 - 13.00",
    namaSiswa: "Nita Fitrotul",
    kelas: "XII MM 1",
    guruBK: "Pak Hermawan",
    jenisSesi: "Online",
    jenisKonseling: "Pendidikan",
    topikKonseling: "Akademik",
    tanggalPengajuan: "13 Oktober 2025",
    tanggalKonseling: "20 Oktober 2025",
    linkGoogleMeet: "https://meet.google.com/xyz-abcd-efg",
    deskripsi: "Siswa ingin konsultasi tentang persiapan ujian akhir semester.",
    status: "Selesai",
    catatanSiswa: "Butuh tips belajar yang efektif untuk persiapan UAS.",
    catatanGuruBK: "Sudah diberikan strategi belajar dan manajemen waktu yang baik.",
  },
  {
    id: 4,
    waktu: "Besok, 14.00 - 15.00",
    namaSiswa: "Najwa Areefa",
    kelas: "X TKJ 3",
    guruBK: "Ibu Wulandari",
    jenisSesi: "Online",
    jenisKonseling: "Pendidikan",
    topikKonseling: "Pribadi",
    tanggalPengajuan: "16 Oktober 2025",
    tanggalKonseling: "21 Oktober 2025",
    linkGoogleMeet: "https://meet.google.com/mno-pqrs-tuv",
    deskripsi: "Siswa merasa kurang percaya diri saat presentasi di kelas.",
    status: "Menunggu",
    catatanSiswa: "",
    catatanGuruBK: "",
  },
  {
    id: 5,
    waktu: "Lusa, 10.00 - 11.00",
    namaSiswa: "Abu Abdirrahman",
    kelas: "XII TKJ 1",
    guruBK: "Guru BK SMK Telkom",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Karir",
    topikKonseling: "Karir",
    tanggalPengajuan: "17 Oktober 2025",
    tanggalKonseling: "22 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa ingin diskusi tentang pilihan perguruan tinggi.",
    status: "Disetujui",
    catatanSiswa: "Ingin mengetahui jurusan yang cocok dengan minat saya.",
    catatanGuruBK: "Siswa memiliki potensi di bidang networking dan sistem administrasi.",
  },
  {
    id: 6,
    waktu: "Lusa, 10.00 - 11.00",
    namaSiswa: "Afad Fath",
    kelas: "XI RPL 3",
    guruBK: "Pak Hermawan",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Karir",
    topikKonseling: "Karir",
    tanggalPengajuan: "18 Oktober 2025",
    tanggalKonseling: "22 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa tertarik untuk magang di perusahaan startup.",
    status: "Menunggu",
    catatanSiswa: "",
    catatanGuruBK: "",
  },
  {
    id: 7,
    waktu: "Lusa, 10.00 - 11.00",
    namaSiswa: "John Doe",
    kelas: "X MM 2",
    guruBK: "Ibu Astuti",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Karir",
    topikKonseling: "Sosial",
    tanggalPengajuan: "17 Oktober 2025",
    tanggalKonseling: "22 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa kesulitan beradaptasi dengan lingkungan sekolah baru.",
    status: "Disetujui",
    catatanSiswa: "Merasa sulit untuk berteman dengan teman sekelas.",
    catatanGuruBK: "Perlu pendampingan untuk meningkatkan kemampuan sosialisasi.",
  },
  {
    id: 8,
    waktu: "Lusa, 10.00 - 11.00",
    namaSiswa: "Alfian Muttakim",
    kelas: "XII TKJ 2",
    guruBK: "Guru BK SMK Telkom",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Karir",
    topikKonseling: "Karir",
    tanggalPengajuan: "19 Oktober 2025",
    tanggalKonseling: "22 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa ingin tahu tentang sertifikasi profesional di bidang IT.",
    status: "Selesai",
    catatanSiswa: "Tertarik mengambil sertifikasi Cisco CCNA.",
    catatanGuruBK: "Sudah diberikan informasi tentang jalur sertifikasi yang tersedia dan prosedurnya.",
  },
  {
    id: 9,
    waktu: "Besok, 11.00 - 12.00",
    namaSiswa: "Ahmad Humaid",
    kelas: "XI RPL 1",
    guruBK: "Pak Hermawan",
    jenisSesi: "Ruang BK",
    jenisKonseling: "Karir",
    topikKonseling: "Karir",
    tanggalPengajuan: "16 Oktober 2025",
    tanggalKonseling: "21 Oktober 2025",
    linkGoogleMeet: "-",
    deskripsi: "Siswa ingin konsultasi tentang peluang kerja sebagai software developer.",
    status: "Disetujui",
    catatanSiswa: "Ingin mengetahui skill yang dibutuhkan untuk menjadi developer profesional.",
    catatanGuruBK: "Siswa menunjukkan kemampuan programming yang baik, perlu diasah lebih lanjut.",
  },
];