export const konsultasiData = [
  {
    id: 1,
    nama: "Nadia Putri Rahmaniar",
    kelas: "XI TKJ 4",
    guru_bk: "Ibu Astuti",
    jenis_sesi: "Online",
    topik: "Karir",
    tanggal: "15 Oktober 2025",
    tanggal_konseling: "18 Oktober 2025",
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    status: "Menunggu",
    link_meet: null,
    hasil_konseling: null,
  },
  {
    id: 2,
    nama: "Nadia Putri Rahmaniar",
    kelas: "XI TKJ 4",
    guru_bk: "Guru bk smk telkom",
    jenis_sesi: "Online",
    topik: "Karir",
    tanggal: "15 Oktober 2025",
    tanggal_konseling: "18 Oktober 2025",
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    status: "Disetujui",
    link_meet: "https://meet.google.com/abc-defg-hij",
    hasil_konseling: null,
  },
  {
    id: 3,
    nama: "Nadia Putri Rahmaniar",
    kelas: "XI TKJ 4",
    guru_bk: "Guru bk smk telkom",
    jenis_sesi: "Online",
    topik: "Karir",
    tanggal: "10 Oktober 2025",
    tanggal_konseling: "12 Oktober 2025",
    deskripsi: "Saya ingin konsultasi mengenai pilihan jurusan kuliah yang sesuai dengan minat dan bakat saya.",
    status: "Selesai",
    link_meet: "https://meet.google.com/xyz-abcd-efg",
    hasil_konseling: "Lorem ipsum dolor sit amet consectetur. Curabitur massa facilisis suspendisse vestibulum pulvinar enim vulputate. Faucibus orci mauris maecenas augue amet nibh.",
  },
  {
    id: 4,
    nama: "Budi Santoso",
    kelas: "XII RPL 2",
    guru_bk: "Pak Hermawan",
    jenis_sesi: "Ruang BK",
    topik: "Akademik",
    tanggal: "20 Oktober 2025",
    tanggal_konseling: null,
    deskripsi: "Saya mengalami kesulitan dalam memahami materi pemrograman dan ingin berdiskusi tentang strategi belajar yang efektif.",
    status: "Menunggu",
    link_meet: null,
    hasil_konseling: null,
  },
  {
    id: 5,
    nama: "Siti Nurhaliza",
    kelas: "X MM 1",
    guru_bk: "Ibu Wulandari",
    jenis_sesi: "Online",
    topik: "Pribadi",
    tanggal: "05 Oktober 2025",
    tanggal_konseling: "08 Oktober 2025",
    deskripsi: "Ingin berbicara tentang cara mengatasi stress dan tekanan dalam kehidupan sekolah.",
    status: "Selesai",
    link_meet: "https://meet.google.com/personal-session",
    hasil_konseling: "Siswa telah diberikan beberapa teknik relaksasi dan manajemen stress. Dianjurkan untuk melakukan olahraga rutin dan mengatur waktu istirahat yang cukup. Follow-up konseling dijadwalkan bulan depan.",
  },
];

export const statusOptions = [
  { value: "Menunggu", label: "Menunggu", color: "warning" },
  { value: "Disetujui", label: "Disetujui", color: "success" },
  { value: "Selesai", label: "Selesai", color: "info" },
  { value: "Ditolak", label: "Ditolak", color: "failure" },
];

export const jenisSesiOptions = [
  { value: "Online", label: "Online (Google Meet)" },
  { value: "Ruang BK", label: "Ruang BK" },
];

export const topikOptions = [
  { value: "Akademik", label: "Akademik" },
  { value: "Karir", label: "Karir" },
  { value: "Pribadi", label: "Pribadi" },
  { value: "Sosial", label: "Sosial" },
  { value: "Lainnya", label: "Lainnya" },
];