export const riwayatKonseling = [
  {
    id: 1,
    tanggal: "15 Oktober 2025",
    namaSiswa: "Alfian",
    nama: "Nadia Putri Rahmaniar",
    kelas: "XI TKJ 4",
    jenisKonseling: "Karir",
    status: "Selesai",
    guruBK: "Guru bk smk telkom",
    jenisSesi: "Online",
    topikKonseling: "Karir",
    tanggalPengajuan: "15 Oktober 2025",
    tanggalKonseling: "20 Oktober 2025",
    waktu: "10.00 - 11.00",
    linkGoogleMeet: "https://meet.google.com/",
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    catatanSiswa: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis. Viverra vitae eu euismod tellus egestas neque. Ultricies habitasse adipiscing non maecenas bibendum cursus vel risus. At egestas massa sed amet scelerisque phasellus. Aliquet turpis velit euismod dignissim praesent integer et elit ullamcorper. In iaculis sapien fringilla vel sociis leo interdum amet. Bibendum velit varius sed sagittis cras arcu. Justo ultricies at nam nulla bibendum erat odio. Maiesuada elit eu proin vitae faucibus nisl pulvinar blandit lacinia.",
    catatanGuruBK: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis. Viverra vitae eu euismod tellus egestas neque. Ultricies habitasse adipiscing non maecenas bibendum cursus vel risus. At egestas massa sed amet scelerisque phasellus. Aliquet turpis velit euismod dignissim praesent integer et elit ullamcorper. In iaculis sapien fringilla vel sociis leo interdum amet. Bibendum velit varius sed sagittis cras arcu. Justo ultricies at nam nulla bibendum erat odio. Maiesuada elit eu proin vitae faucibus nisl pulvinar blandit lacinia."
  },
  {
    id: 2,
    tanggal: "14 Oktober 2025",
    namaSiswa: "Nita",
    nama: "Nita Sari",
    kelas: "XII RPL 2",
    jenisKonseling: "Pendidikan",
    status: "Selesai",
    guruBK: "Guru bk smk telkom",
    jenisSesi: "Offline",
    topikKonseling: "Pendidikan",
    tanggalPengajuan: "14 Oktober 2025",
    tanggalKonseling: "19 Oktober 2025",
    waktu: "13.00 - 14.00",
    linkGoogleMeet: null,
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    catatanSiswa: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis.",
    catatanGuruBK: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis."
  },
  {
    id: 3,
    tanggal: "13 Oktober 2025",
    namaSiswa: "Juna",
    nama: "Juna Pratama",
    kelas: "X MM 1",
    jenisKonseling: "Karir",
    status: "Selesai",
    guruBK: "Guru bk smk telkom",
    jenisSesi: "Online",
    topikKonseling: "Karir",
    tanggalPengajuan: "13 Oktober 2025",
    tanggalKonseling: "18 Oktober 2025",
    waktu: "09.00 - 10.00",
    linkGoogleMeet: "https://meet.google.com/",
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    catatanSiswa: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis.",
    catatanGuruBK: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis."
  },
  {
    id: 4,
    tanggal: "12 Oktober 2025",
    namaSiswa: "Rasyid",
    nama: "Rasyid Hidayat",
    kelas: "XI TKJ 3",
    jenisKonseling: "Pendidikan",
    status: "Selesai",
    guruBK: "Guru bk smk telkom",
    jenisSesi: "Offline",
    topikKonseling: "Pendidikan",
    tanggalPengajuan: "12 Oktober 2025",
    tanggalKonseling: "17 Oktober 2025",
    waktu: "14.00 - 15.00",
    linkGoogleMeet: null,
    deskripsi: "Lorem ipsum dolor sit amet consectetur. Scelerisque risus non nulla volutpat id bibendum.",
    catatanSiswa: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis.",
    catatanGuruBK: "Lorem ipsum dolor sit amet consectetur. Feugiat parturient mi lorem vitae elit massa et mattis."
  }
];